name: Extract JS Endpoints

on:
  workflow_dispatch:

jobs:
  find-js-routes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract and Search JS Files
        run: |
          ZIP_FILE=$(find . -name "*.zip" | head -n 1)
          mkdir -p extracted_files
          unzip -q "$ZIP_FILE" -d extracted_files/
          
          APK_FILE=$(find extracted_files/ -name "*.apk" | head -n 1)
          unzip -q "$APK_FILE" -d unpacked_apk/
          
          echo "========================================="
          echo "[+] الروابط وكلمات الـ API الصريحة داخل ملفات الـ JS:"
          echo "========================================="
          
          # استخراج الروابط بالكامل أو أي نص يحتوي على render أو api داخل مجلد الأستوديو
          grep -oE "https?://[a-zA-Z0-9./_-]+" unpacked_apk/assets/ad-viewer/* | sort -u
          grep -oE "[a-zA-Z0-9_-]*(api|login|auth|v1)[a-zA-Z0-9_-]*" unpacked_apk/assets/ad-viewer/* | sort -u
